### ISSUE TITLE
Error with dimension

### ISSUE THREAD

**Issue by Yucareux** [Querz/FTBChunks2MCASelector#1]
C:\Users\tomyt\Downloads\ftbchunks.3zTp\ftbchunks\world\data\ftbchunks>java -jar ftbchunks2mcaselector.jar . minecraft:overworld
Exception in thread "main" org.json.JSONException: JSONObject["minecraft:overworld"] not found.
        at org.json.JSONObject.get(JSONObject.java:572)
        at org.json.JSONObject.getJSONArray(JSONObject.java:765)
        at net.querz.ftbchunks2mcaselector.Main.main(Main.java:37)

**Comment by Querz** [comment]
[ftbchunks2mcaselector.jar.zip](https://github.com/Querz/mcaselector/files/6272724/ftbchunks2mcaselector.jar.zip)
Added some more debugs and made it not crash when it can't read something.
